
#register test

POST http://localhost:8080/api/customer/register
Content-Type: application/json

{
  "email":"sywon@subutai.com",
  "password": "subutai123!",
  "name": "원성연,",
  "nickName": "수부타이",
  "phoneNumber" : "010-1111-2222"
}
